// <auto-generated />
using System;
using Esoteric.Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esoteric.Finance.Data.Migrations
{
    [DbContext(typeof(EsotericFinanceContext))]
    [Migration("20220810162231_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Dbo.GeneralLog", b =>
                {
                    b.Property<long>("GeneralLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int>("EventCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("GeneralLogId");

                    b.ToTable("GeneralLog", "dbo");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", "Payment");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Correction"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Auto"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Beauty"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bill"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Charity"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Education"
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Entertainment"
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Food"
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gift"
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Health"
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home"
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Income"
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Legal"
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Office"
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pet"
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Shipping"
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Transfer"
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Utilities"
                        });
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Method", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("MethodId");

                    b.ToTable("Method", "Payment");

                    b.HasData(
                        new
                        {
                            MethodId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cash"
                        });
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Recipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipientId");

                    b.ToTable("Recipient", "Payment");

                    b.HasData(
                        new
                        {
                            RecipientId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "IRS"
                        },
                        new
                        {
                            RecipientId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Amazon"
                        },
                        new
                        {
                            RecipientId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Walmart"
                        },
                        new
                        {
                            RecipientId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Target"
                        });
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory", "Payment");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            CategoryId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Correction"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            CategoryId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Miscellaneous"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            CategoryId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tires"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clothes"
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Insurance"
                        },
                        new
                        {
                            SubCategoryId = 6,
                            CategoryId = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tithe"
                        },
                        new
                        {
                            SubCategoryId = 7,
                            CategoryId = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Certificate"
                        },
                        new
                        {
                            SubCategoryId = 8,
                            CategoryId = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Game"
                        },
                        new
                        {
                            SubCategoryId = 9,
                            CategoryId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dine"
                        },
                        new
                        {
                            SubCategoryId = 10,
                            CategoryId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Takeout"
                        },
                        new
                        {
                            SubCategoryId = 11,
                            CategoryId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Drink"
                        },
                        new
                        {
                            SubCategoryId = 12,
                            CategoryId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Snack"
                        },
                        new
                        {
                            SubCategoryId = 13,
                            CategoryId = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Birthday, Mom"
                        },
                        new
                        {
                            SubCategoryId = 14,
                            CategoryId = 11,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Medicine"
                        },
                        new
                        {
                            SubCategoryId = 15,
                            CategoryId = 12,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cleaning Supplies"
                        },
                        new
                        {
                            SubCategoryId = 16,
                            CategoryId = 13,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Paycheck"
                        },
                        new
                        {
                            SubCategoryId = 17,
                            CategoryId = 14,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Taxes"
                        },
                        new
                        {
                            SubCategoryId = 18,
                            CategoryId = 15,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Paper"
                        },
                        new
                        {
                            SubCategoryId = 19,
                            CategoryId = 16,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Litter"
                        },
                        new
                        {
                            SubCategoryId = 20,
                            CategoryId = 17,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stamps"
                        },
                        new
                        {
                            SubCategoryId = 21,
                            CategoryId = 18,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Withdrawal"
                        },
                        new
                        {
                            SubCategoryId = 22,
                            CategoryId = 18,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Deposit"
                        },
                        new
                        {
                            SubCategoryId = 23,
                            CategoryId = 18,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pay Credit Card"
                        },
                        new
                        {
                            SubCategoryId = 24,
                            CategoryId = 19,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gas"
                        },
                        new
                        {
                            SubCategoryId = 25,
                            CategoryId = 20,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Internet"
                        });
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("TargetId");

                    b.ToTable("Transaction", "Payment");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.TransactionMethod", b =>
                {
                    b.Property<long>("TransactionMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int>("MethodId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionMethodId");

                    b.HasIndex("MethodId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionMethod", "Payment");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.TransactionSubCategory", b =>
                {
                    b.Property<long>("TransactionSubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("esoteric-finance-api");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionSubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionSubCategory", "Payment");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.SubCategory", b =>
                {
                    b.HasOne("Esoteric.Finance.Abstractions.Entities.Payment.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Transaction", b =>
                {
                    b.HasOne("Esoteric.Finance.Abstractions.Entities.Payment.Recipient", "Target")
                        .WithMany("Transactions")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.TransactionMethod", b =>
                {
                    b.HasOne("Esoteric.Finance.Abstractions.Entities.Payment.Method", "Method")
                        .WithMany("Transactions")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Esoteric.Finance.Abstractions.Entities.Payment.Transaction", "Transaction")
                        .WithMany("Methods")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.TransactionSubCategory", b =>
                {
                    b.HasOne("Esoteric.Finance.Abstractions.Entities.Payment.SubCategory", "SubCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Esoteric.Finance.Abstractions.Entities.Payment.Transaction", "Transaction")
                        .WithMany("SubCategories")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Method", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Recipient", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.SubCategory", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Esoteric.Finance.Abstractions.Entities.Payment.Transaction", b =>
                {
                    b.Navigation("Methods");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
